CREATE TABLE STUDENTS (

ID INT PRIMARY KEY IDENTITY NOT NULL,
[NAME] NVARCHAR(50) NOT NULL,
SURNAME NVARCHAR(55) DEFAULT 'XXXXXXXX'
)


CREATE TABLE SUBJECTS (

ID INT PRIMARY KEY IDENTITY NOT NULL,
[NAME] NVARCHAR(50) NOT NULL

)

CREATE TABLE EXAMS (

ID INT PRIMARY KEY IDENTITY NOT NULL,
[DATE] DATE NOT NULL,

FOREIGN KEY (ID) REFERENCES SUBJECTS(ID)
)

CREATE TABLE STUDENTEXAMS (

ID INT PRIMARY KEY IDENTITY NOT NULL,
EXAMRESULTS DECIMAL NOT NULL,
StudentID INT,
    ExamID INT,

 FOREIGN KEY (StudentID) REFERENCES STUDENTS(ID),
    FOREIGN KEY (ExamID) REFERENCES EXAMS(ID)
)

SELECT 
    s.Name,
    s.Surname,
  
    e.[DATE],
    se.EXAMRESULTS
FROM 
    STUDENTS s
JOIN 
    STUDENTEXAMS se ON s.ID = se.StudentID
JOIN 
    EXAMS e ON se.ExamID = e.ID






